### ISSUE TITLE
Small issues with the installation instructions

### ISSUE THREAD

**Issue by RoelN** [scribbletone/i-can-variable-font#7]
I followed the instructions on a Mac (El Capitan), some comments:

1. Add to docs that you need to install TTX/FontTools
2. (On Mac) `pip install fontmake` works as well
3. `python env/lib/python2.7/site-packages/fontTools/varLib/__init__.py path-to-your-designspace-file` is `python /usr/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py path-to-your-designspace-file` on (my?) Mac
4. "with -GX in the name" → "with -VF in the name"

**Comment by traviskochel** [comment]
Thanks for these notes. Looks like things have changed a bit since I put these together. I added these changes.

A few notes though, in case you still had questions:

1. Your item 2, using pip to install fontmake, should automatically install fonttools as well.
2. Nice!
3. This command has changed to be much shorter: `fonttools varLib your-designspace-file`, as noted here https://github.com/scribbletone/i-can-variable-font/issues/9
4. thanks

**Comment by RoelN** [comment]
Cheers! Thanks for sharing your notes, this was really helpful in creating my first variable font!
